# Generated by Django 4.1.7 on 2023-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tags',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
