# Generated by Django 4.1.7 on 2023-03-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderdb', '0002_alter_tags_tag_alter_tags_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=300),
        ),
    ]
