# Generated by Django 4.1.7 on 2023-03-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommenderdb', '0004_delete_genome_scores_delete_genome_tags_delete_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genome_Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=20)),
                ('tagId', models.CharField(max_length=20)),
                ('relevance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genome_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=20)),
                ('imdbId', models.CharField(max_length=50)),
                ('tmdbId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('genres', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('movieId', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('movieId', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=300)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
