# Generated by Django 4.1.7 on 2023-03-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderdb', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genome_Scores',
        ),
        migrations.DeleteModel(
            name='Genome_Tags',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
